version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: docker/BackendDockerfile      
    container_name: address-book-backend    
    volumes:
      - .:/app
    ports:
      - "8002:8000"

  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: address-book-frontend
    volumes:
      - ./app:/app
    ports:
      - "8083:80"
    depends_on:
      - django